blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('<pk>/', BlogDetailView.as_view(), name='blog-detail'),
]

cart/urls.py
from django.urls import path, re_path
from .views import (CartView, add_to_cart, remove_from_cart,
                    remove_single_item_from_cart, AddCouponView, CheckoutView, PaymentView)

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='cart'),
    path('add_to_cart/<pk>', add_to_cart, name='add_to_cart'),
    path('add_coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove_from_cart/<pk>', remove_from_cart, name='remove_from_cart'),
    path('remove_item_from_cart/<pk>/',
         remove_single_item_from_cart,
         name='remove_single_item_from_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
]

product/urls.py
from django.urls import path, re_path
from .views import (
    home,
    ProductDetailView,
    productlist,
    contact,
    product_category,
    about_us,
    CompareView,
    add_to_compare,
    remove_from_compare,
    search,
    WishView,
    add_to_wishlist,
    remove_from_wishlist,
    product_subcategory,
    sitemap,
    faq,
)

app_name = 'product'

urlpatterns = [
    path('', home, name='home'),
    path('product/<int:pk>/<slug>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('products/', productlist, name='products'),
    path('contact-us/', contact, name='contact-us'),
    path('products/<int:pk>/<slug>/', product_category, name='category'),
    path('products/<slug>/<int:pk>/<category>/',
         product_subcategory, name='subcategory'),
    path('about-us/', about_us, name='about-us'),
    path('sitemap/', sitemap, name='sitemap'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add_to_compare/<pk>', add_to_compare, name='add_to_compare'),
    path('remove_from_compare/<pk>', remove_from_compare,
         name='remove_from_compare'),
    path('search/', search, name='search'),
    path('wishlist/', WishView.as_view(), name='wishlist'),
    path('add_to_wishlist/<pk>', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<pk>', remove_from_wishlist,
         name='remove_from_wishlist'),
    path('faq/', faq, name='faq'),
]

tpshop/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include,re_path
from django.conf.urls.static import static
from product.views import handler404
from django.contrib import admin
from api.views import TestView
from tpshop import settings



handler404 = handler404
# handler500 = myapp.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root':"path\to\your\static\folder"}),
    path('accounts/', include('allauth.urls')),
    path('',include('product.urls'),name='product'),
    path('cart/',include('cart.urls'),name='cart'),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/',TestView.as_view(),name='api'),
    path('captcha/', include('captcha.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

userprofile/urls.py
from django.urls import path, re_path
from .views import userprofile,OrderDetail,UserOrders,UserAddresses,UserComments,PersonalInfo,datepicker

app_name = 'userprofile'

urlpatterns = [
    path('', userprofile, name='userprofile'),
    path('order-detail/<pk>', OrderDetail, name='order-detail'),
    path('user-orders/', UserOrders, name='user-orders'),
    path('addresses/', UserAddresses, name='user-addresses'),
    path('comments/', UserComments, name='user-comments'),
    path('personal-info/', PersonalInfo, name='personal-info'),
    path('datepicker/', datepicker, name='datepicker'),

    

]

product/views.py
from django.shortcuts import render,  redirect, get_object_or_404, reverse, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import DetailView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.db.models import Q
from .forms import ContactForm, ProductCommentForm
from .decorators import check_recaptcha
from .models import (Product, Category, Subcategory, Compare,
                     CompareItem, Wishlist, WishItem, Contact, ProductComment, Hit)
import datetime
from django.contrib.contenttypes.models import ContentType
from hitcount.views import HitCountDetailView
# Create your views here.
from star_ratings.models import Rating


def render_to_response_hit_count(request, template_path, keys, response):
    for key in keys:
        for i in response[key]:
            Hit(content_object=i).save()
    return render(template_path, response)


def home(request):
    return render(request, 'index.html', {})


def productlist(request):
    order = request.GET.get('order')
    if order:
        products = Product.objects.all().order_by(order)
    else:
        products = Product.objects.all()
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'order': order,
        'page_obj': page_obj,
        'page_number': page_number
    }

    return render(request, 'category.html', context)


def product_category(request, pk, slug):
    qs = Category.objects.get(id=pk, slug=slug)
    order = request.GET.get('order')
    if order:
        pcategory = qs.products.all().order_by(order)
    else:
        pcategory = qs.products.all()
    paginator = Paginator(pcategory, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'order': order,
        'category': qs,
        'page_obj': page_obj,
        'page_number': page_number,
    }
    return render(request, 'pcat.html', context)


def product_subcategory(request, category, pk, slug):
    qs = Subcategory.objects.get(id=pk)
    cqs = Category.objects.get(subcategory=qs)
    order = request.GET.get('order')
    if order:
        pscategory = qs.products.all().order_by(order)
    else:
        pscategory = qs.products.all()
    paginator = Paginator(pscategory, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'category': cqs,
        'subcategory': qs,
        'page_obj': page_obj,
        'page_number': page_number,
        'order': order,
    }
    return render(request, 'psub.html', context)


class ProductDetailView(FormMixin, HitCountDetailView):
    model = Product
    query_pk_and_slug = True
    template_name = 'product.html'
    form_class = ProductCommentForm
    count_hit = True

    def get_success_url(self):
        return reverse('product:product-detail', kwargs={'pk': self.object.id, 'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['form'] = ProductCommentForm(initial={'product': self.object})
        context['comments'] = self.object.comments.filter(
            approved=True, parent=None).order_by('-date')
        context['rating'] = Rating.objects.get(
            object_id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            parent_obj = None
            # get parent comment id from hidden input
            try:
                # id integer e.g. 15
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            # if parent_id has been submitted get parent_obj id
            if parent_id:
                parent_obj = ProductComment.objects.get(id=parent_id)
                replay_comment = form.save(commit=False)
                # assign parent_obj to replay comment
                replay_comment.parent = parent_obj
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(ProductDetailView, self).form_valid(form)


class CompareView(View):
    def get(self, *args, **kwargs):
        try:
            compare = Compare.objects.get(
                user=self.request.user)
            context = {'object': compare}
            return render(self.request, 'compare.html', context)
        except ObjectDoesNotExist:
            messages.error(
                self.request, 'شما محصولی در لیست مقایسه خود ندارید .')
            return redirect(self.request.META.get('HTTP_REFERER'))


def add_to_compare(request, pk):
    product = get_object_or_404(Product, id=pk)
    compare_item, created = CompareItem.objects.get_or_create(
        product=product,
        user=request.user,
    )
    compare_qs = Compare.objects.filter(user=request.user)
    if compare_qs.exists():
        compare = compare_qs[0]
        if compare.products.filter(product__id=product.id).exists():
            pass
        else:
            compare.products.add(compare_item)
            messages.info(
                request, f'{compare_item.product.name} به لیست مقایسه افزوده شد .')
            redirect(request.META.get('HTTP_REFERER'))
    else:
        compare = Compare.objects.create(user=request.user,
                                         )
        compare.products.add(compare_item)
        messages.info(
            request, f'{compare_item.product.name} به لیست مقایسه افزوده شد .')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))


def remove_from_compare(request, pk):
    product = get_object_or_404(Product, id=pk)
    order_qs = Compare.objects.filter(
        user=request.user,
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__id=product.id).exists():
            order_item = CompareItem.objects.filter(
                product=product,
                user=request.user,
            )[0]
            order.products.remove(order_item)
            order_item.delete()
            messages.warning(
                request, f"{order_item.product.name} از لیست مقایسه شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.warning(
                request,  f"{order_item.product.name} از لیست مقایسه شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.warning(request, "شما محصولی در لیست مقایسه خود ندارید .")
        return redirect(request.META.get('HTTP_REFERER'))


class WishView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            wish = Wishlist.objects.get(
                user=self.request.user)
            context = {'object': wish}
            return render(self.request, 'wishlist.html', context)
        except ObjectDoesNotExist:
            messages.error(
                self.request, 'شما محصولی در لیست علاقه مندی خود ندارید .')
            return redirect(self.request.META.get('HTTP_REFERER'))


@login_required
def add_to_wishlist(request, pk):
    product = get_object_or_404(Product, id=pk)
    wish_item, created = WishItem.objects.get_or_create(
        product=product,
        user=request.user,
    )
    wish_qs = Wishlist.objects.filter(user=request.user)
    if wish_qs.exists():
        wish = wish_qs[0]
        if wish.products.filter(product__id=product.id).exists():
            pass
        else:
            wish.products.add(wish_item)
            messages.info(
                request, f'{wish_item.product.name} به لیست علاقه مندی ها افزوده شد .')
            redirect(request.META.get('HTTP_REFERER'))
    else:
        wish = Wishlist.objects.create(user=request.user,
                                       )
        wish.products.add(wish_item)
        messages.info(
            request, f'{wish_item.product.name} به لیست علاقه مندی ها افزوده شد .')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def remove_from_wishlist(request, pk):
    product = get_object_or_404(Product, id=pk)
    order_qs = Wishlist.objects.filter(
        user=request.user,
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__id=product.id).exists():
            order_item = WishItem.objects.filter(
                product=product,
                user=request.user,
            )[0]
            order.products.remove(order_item)
            order_item.delete()
            messages.warning(
                request, f"{order_item.product.name} از لیست علاقه مندی های شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.warning(
                request, f"{order_item.product.name} از لیست علاقه مندی های شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.warning(request, 'شما محصولی در لیست علاقه مندی خود ندارید .')

product/templates/includes/footer.html
{% load static %}
<!--Footer Start-->
<footer id="footer">
  <div class="fpart-first">
    <div class="container">
      <div class="row">
        <div class="contact col-lg-4 col-md-4 col-sm-12 col-xs-12">
          <h5>اطلاعات تماس</h5>
          <ul>
            <li class="address"><i class="fa fa-map-marker"></i>استان گلستان  گرگان</li>
            <li class="mobile"><i class="fa fa-phone"></i>09918797376</li>
            <li class="email"><i class="fa fa-envelope"></i>برقراری ارتباط از طریق <a href="{% url 'product:contact-us' %}">تماس با ما</a>
          </ul>
        </div>
        <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
          <h5>اطلاعات</h5>
          <ul>
            <li><a href="{% url 'product:about-us' %}">درباره ما</a></li>
            <li><a href="about-us.html">اطلاعات ارسال</a></li>
            <li><a href="about-us.html">حریم خصوصی</a></li>
            <li><a href="about-us.html">شرایط و قوانین</a></li>
          </ul>
        </div>
        <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
          <h5>خدمات مشتریان</h5>
          <ul>
            <li><a href="{% url 'product:contact-us' %}">تماس با ما</a></li>
            <li><a href="{% url 'product:faq' %}">سوالات متداول</a></li>
            <li><a href="{% url 'product:sitemap' %}">نقشه سایت</a></li>
          </ul>
        </div>
        <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
          <h5>امکانات جانبی</h5>
          <ul>
            <li><a href="#">برند ها</a></li>
            <li><a href="#">کارت هدیه</a></li>
            <li><a href="#">بازاریابی</a></li>
            <li><a href="#">ویژه ها</a></li>
          </ul>
        </div>
        <div class="column col-lg-2 col-md-2 col-sm-3 col-xs-12">
          <h5>حساب من</h5>
          <ul>
            <li><a href="#">حساب کاربری</a></li>
            <li><a href="#">تاریخچه سفارشات</a></li>
            <li><a href="#">لیست علاقه مندی</a></li>
            <li><a href="#">خبرنامه</a></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="fpart-second">
    <div class="container">
      <div id="powered" class="clearfix">
        <div class="powered_text pull-left flip">
          <p>کپی رایت © 2020</p>
        </div>
        <div class="social pull-right flip"> <a href="#" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/facebook.png' %}" alt="Facebook" title="Facebook"></a> <a href="#" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/twitter.png' %}" alt="Twitter" title="Twitter"> </a> <a href="#" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/google_plus.png' %}" alt="Google+" title="Google+"> </a> <a href="#" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/pinterest.png' %}" alt="Pinterest" title="Pinterest"> </a> <a href="#" target="_blank"> <img data-toggle="tooltip" src="{% static 'image/socialicons/rss.png' %}" alt="RSS" title="RSS"> </a> </div>
      </div>
      <div class="bottom-row">
        <div class="custom-text text-center">
          <p>این یک بلاک مدیریت محتواست. شما میتوانید هر نوع محتوای html نوشتاری یا تصویری را در آن قرار دهید. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
        </div>
    </div>
  </div>
  <div id="back-top"><a data-toggle="tooltip" title="بازگشت به بالا" href="javascript:void(0)" class="backtotop"><i class="fa fa-chevron-up"></i></a></div>
</footer>
<!--Footer End-->

product/templates/includes/navbar.html
{% load static %}
{% load cart_tag %}
{% load wishlist_tag %}
<div id="header">
  <!-- Top Bar Start-->
  <nav id="top" class="htop">
    <div class="container">
      <div class="row"> <span class="drop-icon visible-sm visible-xs"><i class="fa fa-align-justify"></i></span>
        <div class="pull-left flip left-top">
          <div class="links">
            <ul>
              <li class="wrap_custom_block hidden-sm hidden-xs"><a>وبلاگ<b></b></a>
                <div class="dropdown-menu custom_block">
                  <ul>
                    <li>
                      <table>
                        <tbody>
                          <tr>
                            {% for blog in blogs %}
                            <td><img alt="" src="{{ blog.blog_image.url }}" style="width: 250px;height: 130;"></td>
                            {% endfor %}
                          </tr>
                          <tr>
                            {% for blog in blogs %}
                            <td>
                              <h4>{{blog.title}}</h4>
                            </td>
                            {% endfor %}
                          </tr>
                          <tr>
                            {% for blog in blogs %}
                            <td style="vertical-align: top;">
                              <p>{{blog.short_desc}}</p>
                            </td>
                            {% endfor %}
                          </tr>
                          <tr>
                            {% for blog in blogs %}
                            <td><strong><a class="btn btn-default btn-sm"
                                  href="{% url 'blog:blog-detail' pk=blog.id %}">ادامه مطلب</a></strong></td>
                            {% endfor %}
                          </tr>
                        </tbody>
                      </table>
                    </li>
                  </ul>
                </div>
              </li>
              {% if user.is_authenticated %}
              <li><a href="{% url 'product:wishlist' %}">لیست علاقه مندی (
                  {{ request.user | wishlist_product_count }})</a></li>
              <li><a href="{% url 'cart:cart' %}">سبد خرید</a></li>
              <li><a href="{% url 'cart:checkout' %}">تسویه حساب</a></li>
              {% endif %}
            </ul>
          </div>
        </div>
        <div id="top-links" class="nav pull-right flip" style="border-right: none;">
          <ul>
            {% if not user.is_authenticated %}
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-2x fa-user" aria-hidden="true"></i>
              <!-- <span class="caret"></span>-->
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="{% url 'account_login' %}">ورود</a></li>
                <li><a href="{% url 'account_signup' %}">ثبت نام</a></li>
              </ul>
            </div>
            {% else %}
            <div class="dropdown">
              <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown"><i class="fa fa-2x fa-user" aria-hidden="true"></i>
              <!-- <span class="caret"></span>-->
              </button>
              <ul class="dropdown-menu pull-right">
                <li><a href="{% url 'userprofile:userprofile' %}">{{user.username}}</a></li>
                <li><a href="#">تغییر رمز عبور</a></li>
                <li><a data-toggle="modal" data-target="#logoutmodal">
                  خروج از حساب کاربری
                </a></li>
              </ul>
            </div> 
            

            {% endif %}
          </ul>
        </div>
      </div>
    </div>
  </nav>
  <!-- Top Bar End-->
  <!-- Header Start-->
  <header class="header-row">
    <div class="container">
      <div class="table-container">
        <!-- Logo Start -->
        <div class="col-table-cell col-lg-6 col-md-6 col-sm-12 col-xs-12 inner">
          <div id="logo"><a href="{% url 'product:home' %}"><img class="img-responsive" style="padding-right: 20px;"
                src="{% static 'image/images.jpeg' %}" title="MarketShop" alt="MarketShop" /></a></div>
        </div>
        <!-- Logo End -->
        <!-- Mini Cart Start-->
        <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12">
          <div id="cart">
            <button type="button" data-toggle="dropdown" data-loading-text="Loading..." class="heading dropdown-toggle">
              <span data-toggle="tooltip" data-placement="top" title="سبد خرید" class="cart-icon pull-left flip"></span>
              <span id="cart-total">
                {% if order2.get_total_with_coupon %}
                {{ request.user | cart_product_count }} آیتم -
                {{ order2.get_total_with_coupon }} تومان
                {% endif %}
              </span>
            </button>
            {% if user.is_authenticated %}
            <ul class="dropdown-menu  pre-scrollable">
              <li>
                <table class="table">
                  <tbody>
                    {% for order_item in order2.products.all %}
                    <tr>
                      <!-- <td class="text-center"><a href="product.html"><img class="img-thumbnail" title="کفش راحتی مردانه" alt="کفش راحتی مردانه" src="{{ order_item.product.miniimage.url }}"></a></td> -->
                      <td class="text-left"><a href="product.html">{{ order_item.product.name }}</a></td>
                      <td class="text-right" style="width:fit-content">x {{ order_item.quantity }}</td>
                      <td class="text-right">
                        {% if order_item.product.discount_price %}
                        {{ order_item.get_total_product_discount_price }} تومان
                        {% else %}
                        {{ order_item.get_total_product_price }} تومان
                        {% endif %}
                      </td>
                      <td class="text-center">
                        <a href="{{ order_item.product.get_remove_from_cart_url }}">
                          <button class="btn btn-danger"><i class="fa fa-trash" aria-hidden="true"
                              style="vertical-align: middle;"></i>
                          </button>
                        </a>
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </li>
              <li>
                <div>
                  <table class="table table-bordered">
                    <tbody>
                      <tr>
                        <td class="text-right"><strong>جمع کل</strong></td>
                        <td class="text-right">
                          {% if order2.get_total %}
                          {{ order2.get_total }} تومان
                          {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <td class="text-right"><strong>کسر هدیه</strong></td>
                        <td class="text-right">
                          {% if order2.coupon.amount %}
                          {{ order2.coupon.amount }} - تومان
                          {% endif %}
                        </td>
                      </tr>
                      <tr>
                        <td class="text-right"><strong>قابل پرداخت</strong></td>
                        <td class="text-right">
                          {% if order2.get_total_with_coupon %}
                          {{ order2.get_total_with_coupon }} تومان
                          {% endif %}
                        </td>
                      </tr>
                    </tbody>
                  </table>
                  <p class="checkout"><a href="{% url 'cart:cart' %}" class="btn btn-primary"><i
                        class="fa fa-shopping-cart"></i> مشاهده سبد</a>&nbsp;&nbsp;&nbsp;<a
                      href="{% url 'cart:checkout' %}" class="btn btn-primary"><i class="fa fa-share"></i> تسویه
                      حساب</a></p>
                </div>
              </li>
            </ul>
            {% endif %}
          </div>
        </div>
        <!-- Mini Cart End-->
        <!-- جستجو Start-->
        <div class="col-table-cell col-lg-3 col-md-3 col-sm-6 col-xs-12 inner">
          <div id="search" class="input-group">
            <form method="GET" action="{% url 'product:search' %}">
              <input id="filter_name" type="text" name="search" placeholder="جستجو" class="form-control input-lg" />
              <button type="submit" class="button-search"><i class="fa fa-search"></i></button>
            </form>
          </div>
        </div>
        <!-- جستجو End-->
      </div>
    </div>
  </header>
  <!-- Header End-->
  <!-- Main آقایانu Start-->
  <div class="container">
    <nav id="menu" class="navbar">
      <div class="navbar-header"> <span class="visible-xs visible-sm"> منو <b></b></span></div>
      <div class="collapse navbar-collapse navbar-ex1-collapse">
        <ul class="nav navbar-nav">
          <li><a class="home_link" title="خانه" href="/"><span>خانه</span></a></li>
          <li class="mega-menu dropdown"><a href="{% url 'product:products' %}">دسته ها</a>
            <div class="dropdown-menu">
              {% for category in categories %}
              <div class="column col-lg-2 col-md-3"><a href="{{ category.get_absolute_url }}">{{ category.title }}</a>
                <div>
                  <ul>
                    {% for sub in category.subcategory.all %}
                    <li><a href="{{ sub.get_absolute_url }}">{{ sub.title }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
              </div>
              {% endfor %}
            </div>
          </li>
          <!-- <li class="menu_brands dropdown"><a href="#">عرضه کنندگان</a>
              <div class="dropdown-menu">
                <div class="col-lg-1 col-md-2 col-sm-3 col-xs-6"><a href="#"><img src="image/product/apple_logo-60x60.jpg" title="اپل" alt="اپل" /></a><a href="#">اپل</a></div>
              </div>
            </li> -->
          <li class="hidden-lg hidden-md"><a href="{% url 'blog:blog' %}">وبلاگ</a>
          <li class="dropdown wrap_custom_block hidden-sm hidden-xs"><a href="{% url 'blog:blog' %}">وبلاگ</a>
            <div class="dropdown-menu custom_block">
              <ul>
                <li>
                  <table>
                    <tbody>
                      <tr>
                        {% for blog in blogs %}
                        <td><img alt="" src="{{ blog.blog_image.url }}" style="width: 250px;height: 130;"></td>
                        {% endfor %}
                      </tr>
                      <tr>
                        {% for blog in blogs %}
                        <td>
                          <h4>{{blog.title}}</h4>
                        </td>
                        {% endfor %}
                      </tr>
                      <tr>
                        {% for blog in blogs %}
                        <td style="vertical-align: top;">{{blog.short_desc}}</td>
                        {% endfor %}
                      </tr>
                      <tr>
                        {% for blog in blogs %}
                        <td><strong><a class="btn btn-default btn-sm"
                              href="{% url 'blog:blog-detail' pk=blog.id %}">ادامه مطلب</a></strong></td>
                        {% endfor %}
                      </tr>
                    </tbody>
                  </table>
                </li>
              </ul>
            </div>
          </li>
          <li class="contact-link"><a href="{% url 'product:contact-us' %}">تماس با ما</a></li>
          <li class="custom-link-right"><a title=" جستجوی محصولات " href="{% url 'product:search' %}"><i
                class="fa fa-lg fa-search" aria-hidden="true"></i> جستجوی محصولات </a></li>
        </ul>
      </div>
    </nav>
  </div>
  <!-- Modal -->
  <div class="modal fade" id="logoutmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <strong>
            <h4 class="modal-title" id="exampleModalLabel">خروج از حساب
              <button class="close" data-dismiss="modal" aria-label="Close">
                <i class="fa fa-times" aria-hidden="true"></i>
              </button>
            </h4>
          </strong>
        </div>
        <div class="modal-body">
          آیا از خروج اطمینان دارید ؟
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
          <form method="post" action="{% url 'account_logout' %}">
            {% csrf_token %}
            {% if redirect_field_value %}
            <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
            {% endif %}
            <button type="submit" class="btn btn-danger" style="font-weight: 500;width: 90px;">خروج از حساب</button>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>