blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('<pk>/', BlogDetailView.as_view(), name='blog-detail'),
]

product/urls.py
from django.urls import path, re_path
from .views import (
    home,
    ProductDetailView,
    productlist,
    contact,
    product_category,
    about_us,
    CompareView,
    add_to_compare,
    remove_from_compare,
    search,
    WishView,
    add_to_wishlist,
    remove_from_wishlist,
    product_subcategory,
    sitemap,
    faq,
)

app_name = 'product'

urlpatterns = [
    path('', home, name='home'),
    path('product/<int:pk>/<slug>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('products/', productlist, name='products'),
    path('contact-us/', contact, name='contact-us'),
    path('products/<int:pk>/<slug>/', product_category, name='category'),
    path('products/<slug>/<int:pk>/<category>/',
         product_subcategory, name='subcategory'),
    path('about-us/', about_us, name='about-us'),
    path('sitemap/', sitemap, name='sitemap'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add_to_compare/<pk>', add_to_compare, name='add_to_compare'),
    path('remove_from_compare/<pk>', remove_from_compare,
         name='remove_from_compare'),
    path('search/', search, name='search'),
    path('wishlist/', WishView.as_view(), name='wishlist'),
    path('add_to_wishlist/<pk>', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<pk>', remove_from_wishlist,
         name='remove_from_wishlist'),
    path('faq/', faq, name='faq'),
]

tpshop/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include,re_path
from django.conf.urls.static import static
from product.views import handler404
from django.contrib import admin
from api.views import TestView
from tpshop import settings



handler404 = handler404
# handler500 = myapp.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root':"path\to\your\static\folder"}),
    path('accounts/', include('allauth.urls')),
    path('',include('product.urls'),name='product'),
    path('cart/',include('cart.urls'),name='cart'),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/',TestView.as_view(),name='api'),
    path('captcha/', include('captcha.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

product/forms.py
from allauth.account.forms import LoginForm, SignupForm, ResetPasswordForm, PasswordField
from allauth.account import app_settings
from django import forms
from django.utils.translation import gettext
from django.forms import ModelForm
from .models import Contact, ProductComment
# need django-simple-captcha module
from captcha.fields import CaptchaField


class CustomLoginForm(LoginForm):
    password = PasswordField(label=("رمز عبور"))
    error_messages = {
        'account_inactive':
        ("این حساب در حال حاضر غیرفعال است ."),

        'email_password_mismatch':
        ("آدرس ایمیل یا رمز عبور وارد شده اشتباه است ."),

        'username_password_mismatch':
        ("نام کابری یا رمز عبور اشتباه است ."),
    }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        login_widget = forms.TextInput(attrs={'placeholder':
                                              ('نام کاربری'),
                                              'autofocus': 'autofocus'})
        username = forms.CharField(
            label=("نام کاربری"),
            widget=login_widget,
            max_length=100)

        self.fields["login"] = username


class CustomSignupForm(SignupForm):
    username = forms.CharField(label=("نام کاربری"),
                               #    min_length=app_settings.USERNAME_MIN_LENGTH,
                               widget=forms.TextInput(
                                   attrs={'placeholder':
                                          ('نام کاربری'),
                                          'autofocus': 'autofocus'}))
    field_order = [
        'username',
        'email',
        'email2',  # ignored when not present
        'password1',
        'password2'  # ignored when not present
    ]

    def __init__(self, *args, **kwargs):
        super(CustomSignupForm, self).__init__(*args, **kwargs)
        self.fields['password1'] = PasswordField(label=("رمز عبور"))
        self.fields['password2'] = PasswordField(label=("تکرار رمز عبور"))
        self.fields['email'].label = gettext("ایمیل")


class CustomResetPasswordForm(ResetPasswordForm):
    email = forms.EmailField(
        label=("پست الکترونیک"),
        required=True,
        widget=forms.TextInput(
            attrs={"type": "email",
                   "size": "30",
                   "placeholder": ('آدرس پست الکترونیک')}))


class ContactForm(forms.ModelForm):
    name = forms.CharField(label="نام شما ", widget=forms.TextInput(attrs={
        'class': "form-control",
    }))
    email = forms.EmailField(label="ایمیل", widget=forms.EmailInput(attrs={
        'class': "form-control",
    }))
    message = forms.CharField(label="پیام شما", widget=forms.Textarea(attrs={
        'class': "form-control",
    }))

    class Meta:
        model = Contact
        fields = "__all__"


class ProductCommentForm(forms.ModelForm):
    # username=forms.CharField(label="نام شما ", widget=forms.TextInput(attrs={
    #     'class': "form-control",
    #     }))
    # message=forms.CharField(label="پیام شما" , widget=forms.Textarea(attrs={
    #     'class': "form-control",
    #     }))
    # # captcha = CaptchaField(label="کد امنیتی ")
    # product=forms.CharField(widget=forms.HiddenInput())
    class Meta:
        model = ProductComment
        fields = '__all__'
        exclude = ('approved', 'parent')
        widgets = {
            'product': forms.HiddenInput(),
            'username': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'message': forms.Textarea(attrs={
                'class': "form-control",
            }),
        }

        labels = {
            'username': 'نام شما',
            'message': 'نظر شما',
        }

product/views.py
from django.shortcuts import render,  redirect, get_object_or_404, reverse, HttpResponse
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import DetailView, ListView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.db.models import Q
from .forms import ContactForm, ProductCommentForm
from .decorators import check_recaptcha
from .models import (Product, Category, Subcategory, Compare,
                     CompareItem, Wishlist, WishItem, Contact, ProductComment, Hit)
import datetime
from django.contrib.contenttypes.models import ContentType
from hitcount.views import HitCountDetailView
# Create your views here.
from star_ratings.models import Rating


def render_to_response_hit_count(request, template_path, keys, response):
    for key in keys:
        for i in response[key]:
            Hit(content_object=i).save()
    return render(template_path, response)


def home(request):
    return render(request, 'index.html', {})


def productlist(request):
    order = request.GET.get('order')
    if order:
        products = Product.objects.all().order_by(order)
    else:
        products = Product.objects.all()
    paginator = Paginator(products, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'order': order,
        'page_obj': page_obj,
        'page_number': page_number
    }

    return render(request, 'category.html', context)


def product_category(request, pk, slug):
    qs = Category.objects.get(id=pk, slug=slug)
    order = request.GET.get('order')
    if order:
        pcategory = qs.products.all().order_by(order)
    else:
        pcategory = qs.products.all()
    paginator = Paginator(pcategory, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'order': order,
        'category': qs,
        'page_obj': page_obj,
        'page_number': page_number,
    }
    return render(request, 'pcat.html', context)


def product_subcategory(request, category, pk, slug):
    qs = Subcategory.objects.get(id=pk)
    cqs = Category.objects.get(subcategory=qs)
    order = request.GET.get('order')
    if order:
        pscategory = qs.products.all().order_by(order)
    else:
        pscategory = qs.products.all()
    paginator = Paginator(pscategory, 4)
    page_number = request.GET.get('page')
    try:
        page_obj = paginator.page(page_number)
    except PageNotAnInteger:
        page_obj = paginator.page(1)
    except EmptyPage:
        page_obj = paginator.page(paginator.num_pages)
    context = {
        'category': cqs,
        'subcategory': qs,
        'page_obj': page_obj,
        'page_number': page_number,
        'order': order,
    }
    return render(request, 'psub.html', context)


class ProductDetailView(FormMixin, HitCountDetailView):
    model = Product
    query_pk_and_slug = True
    template_name = 'product.html'
    form_class = ProductCommentForm
    count_hit = True

    def get_success_url(self):
        return reverse('product:product-detail', kwargs={'pk': self.object.id, 'slug': self.object.slug})

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context['form'] = ProductCommentForm(initial={'product': self.object})
        context['comments'] = self.object.comments.filter(
            approved=True, parent=None).order_by('-date')
        context['rating'] = Rating.objects.get(
            object_id=self.object.id)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            parent_obj = None
            # get parent comment id from hidden input
            try:
                # id integer e.g. 15
                parent_id = int(request.POST.get('parent_id'))
            except:
                parent_id = None
            # if parent_id has been submitted get parent_obj id
            if parent_id:
                parent_obj = ProductComment.objects.get(id=parent_id)
                replay_comment = form.save(commit=False)
                # assign parent_obj to replay comment
                replay_comment.parent = parent_obj
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        form.save()
        return super(ProductDetailView, self).form_valid(form)


class CompareView(View):
    def get(self, *args, **kwargs):
        try:
            compare = Compare.objects.get(
                user=self.request.user)
            context = {'object': compare}
            return render(self.request, 'compare.html', context)
        except ObjectDoesNotExist:
            messages.error(
                self.request, 'شما محصولی در لیست مقایسه خود ندارید .')
            return redirect(self.request.META.get('HTTP_REFERER'))


def add_to_compare(request, pk):
    product = get_object_or_404(Product, id=pk)
    compare_item, created = CompareItem.objects.get_or_create(
        product=product,
        user=request.user,
    )
    compare_qs = Compare.objects.filter(user=request.user)
    if compare_qs.exists():
        compare = compare_qs[0]
        if compare.products.filter(product__id=product.id).exists():
            pass
        else:
            compare.products.add(compare_item)
            messages.info(
                request, f'{compare_item.product.name} به لیست مقایسه افزوده شد .')
            redirect(request.META.get('HTTP_REFERER'))
    else:
        compare = Compare.objects.create(user=request.user,
                                         )
        compare.products.add(compare_item)
        messages.info(
            request, f'{compare_item.product.name} به لیست مقایسه افزوده شد .')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))


def remove_from_compare(request, pk):
    product = get_object_or_404(Product, id=pk)
    order_qs = Compare.objects.filter(
        user=request.user,
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__id=product.id).exists():
            order_item = CompareItem.objects.filter(
                product=product,
                user=request.user,
            )[0]
            order.products.remove(order_item)
            order_item.delete()
            messages.warning(
                request, f"{order_item.product.name} از لیست مقایسه شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.warning(
                request,  f"{order_item.product.name} از لیست مقایسه شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.warning(request, "شما محصولی در لیست مقایسه خود ندارید .")
        return redirect(request.META.get('HTTP_REFERER'))


class WishView(LoginRequiredMixin, View):
    def get(self, *args, **kwargs):
        try:
            wish = Wishlist.objects.get(
                user=self.request.user)
            context = {'object': wish}
            return render(self.request, 'wishlist.html', context)
        except ObjectDoesNotExist:
            messages.error(
                self.request, 'شما محصولی در لیست علاقه مندی خود ندارید .')
            return redirect(self.request.META.get('HTTP_REFERER'))


@login_required
def add_to_wishlist(request, pk):
    product = get_object_or_404(Product, id=pk)
    wish_item, created = WishItem.objects.get_or_create(
        product=product,
        user=request.user,
    )
    wish_qs = Wishlist.objects.filter(user=request.user)
    if wish_qs.exists():
        wish = wish_qs[0]
        if wish.products.filter(product__id=product.id).exists():
            pass
        else:
            wish.products.add(wish_item)
            messages.info(
                request, f'{wish_item.product.name} به لیست علاقه مندی ها افزوده شد .')
            redirect(request.META.get('HTTP_REFERER'))
    else:
        wish = Wishlist.objects.create(user=request.user,
                                       )
        wish.products.add(wish_item)
        messages.info(
            request, f'{wish_item.product.name} به لیست علاقه مندی ها افزوده شد .')
        return redirect(request.META.get('HTTP_REFERER'))
    return redirect(request.META.get('HTTP_REFERER'))


@login_required
def remove_from_wishlist(request, pk):
    product = get_object_or_404(Product, id=pk)
    order_qs = Wishlist.objects.filter(
        user=request.user,
    )
    if order_qs.exists():
        order = order_qs[0]
        if order.products.filter(product__id=product.id).exists():
            order_item = WishItem.objects.filter(
                product=product,
                user=request.user,
            )[0]
            order.products.remove(order_item)
            order_item.delete()
            messages.warning(
                request, f"{order_item.product.name} از لیست علاقه مندی های شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            messages.warning(
                request, f"{order_item.product.name} از لیست علاقه مندی های شما حذف شد !")
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        messages.warning(request, 'شما محصولی در لیست علاقه مندی خود ندارید .')

product/templates/about-us.html
{% extends 'base1.html' %} {% load static %}
{% block title %}<title>درباره ما</title>{% endblock %}
{% block body %}
<div id="container">
  <div class="container">
    <!-- Breadcrumb Start-->
    <ul class="breadcrumb">
      <li><a href="/"><i class="fa fa-home"></i></a></li>
      <li><a href="{% url 'product:about-us' %}">درباره ما</a></li>
    </ul>
    <!-- Breadcrumb End-->
    <div class="row">
      <!--Middle Part Start-->
      <div id="content" class="col-sm-12">
        <h1 class="title">درباره ما</h1>
        <div class="row">
          <div class="col-sm-12">
            <p>شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی
              الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری
              موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و
              جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد.</p>
            <p>شناخت فراوان جامعه و متخصصان را می طلبد تا با نرم افزارها شناخت بیشتری را برای طراحان رایانه ای علی
              الخصوص طراحان خلاقی و فرهنگ پیشرو در زبان فارسی ایجاد کرد. در این صورت می توان امید داشت که تمام و دشواری
              موجود در ارائه راهکارها و شرایط سخت تایپ به پایان رسد وزمان مورد نیاز شامل حروفچینی دستاوردهای اصلی و
              جوابگوی سوالات پیوسته اهل دنیای موجود طراحی اساسا مورد استفاده قرار گیرد. لورم ایپسوم متن ساختگی با تولید
              سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و
              سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی
              می باشد. </p>
            <blockquote>
              <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و
                متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و
                کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد. </p>
              <footer>ایپسوم دولور سیت</footer>
            </blockquote>
            <p>لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با استفاده از طراحان گرافیک است. چاپگرها و
              متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای شرایط فعلی تکنولوژی مورد نیاز و کاربردهای
              متنوع با هدف بهبود ابزارهای کاربردی می باشد.لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
              استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای
              شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
          </div>
        </div>
        <h3 class="text-center">متن دلخواه خود را در اینجا قرار دهید.</h3>
        <div class="row">
          <div class="col-sm-4">
            <div class="well">
              <h4>ارسال رایگان</h4>
              <p>متن دلخواه خود را در اینجا قرار دهید. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای
                شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
              <a href="#" class="btn btn-primary">ادامه مطلب</a>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="well">
              <h4>کارت هدیه</h4>
              <p>متن دلخواه خود را در اینجا قرار دهید. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای
                شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
              <a href="#" class="btn btn-primary">ادامه مطلب</a>
            </div>
          </div>
          <div class="col-sm-4">
            <div class="well">
              <h4>امتیازات خرید</h4>
              <p>متن دلخواه خود را در اینجا قرار دهید. لورم ایپسوم متن ساختگی با تولید سادگی نامفهوم از صنعت چاپ و با
                استفاده از طراحان گرافیک است. چاپگرها و متون بلکه روزنامه و مجله در ستون و سطرآنچنان که لازم است و برای
                شرایط فعلی تکنولوژی مورد نیاز و کاربردهای متنوع با هدف بهبود ابزارهای کاربردی می باشد.</p>
              <a href="#" class="btn btn-primary">ادامه مطلب</a>
            </div>
          </div>
        </div>
      </div>
      <!--Middle Part End -->
    </div>
  </div>
</div>
{% endblock %}

product/templates/category.html
{% extends 'base1.html' %}
{% load templatehelpers %}
{% load compare_tag %}
{% load static %}
{% block title %}<title>محصولات</title>{% endblock %}
{% block body %}
<div id="container">
  <div class="container">
    <!-- Breadcrumb Start-->
    <ul class="breadcrumb">
      <li><a href="/"><i class="fa fa-home"></i></a></li>
      <li><a href="{% url 'product:products' %}">همه محصولات</a></li>
    </ul>
    <!-- Breadcrumb End-->
    <div class="row">
      <!--Left Part Start -->
      {% include 'includes/sidebar.html' %}
      <!--Left Part End -->
      <!--Middle Part Start-->
      <div id="content" class="col-sm-9">
        <h1 class="title">همه محصولات</h1>
        <hr>
        <div class="product-filter">
          <div class="row">
            <div class="col-md-4 col-sm-5">
              <div class="btn-group">
                <button type="button" id="list-view" class="btn btn-default" data-toggle="tooltip" title="List"><i
                    class="fa fa-th-list"></i></button>
                <button type="button" id="grid-view" class="btn btn-default" data-toggle="tooltip" title="Grid"><i
                    class="fa fa-th"></i></button>
              </div>
              <a href="{% url 'product:compare' %}" id="compare-total">محصولات مقایسه
                ({{ request.user | compare_product_count }})</a>
            </div>
            <form id="FORM_ID" method="GET" action="{% url 'product:products' %}">
              <div class="col-sm-2 text-right">
                <label class="control-label" for="input-sort">مرتب سازی :</label>
              </div>
              <div class="col-md-3 col-sm-3 text-right">
                <select onchange="this.form.submit()" name="order" class="form-control">
                  <option value="name" {% if order == "name" %} selected {% endif %}>پیشفرض</option>
                  <option value="name" {% if order == "name" %} selected {% endif %}>نام (الف - ی)</option>
                  <option value="-name" {% if order == "-name" %} selected {% endif %}>نام (ی - الف)</option>
                  <option value="price" {% if order == "price" %} selected {% endif %}>قیمت (کم به زیاد)</option>
                  </option>
                  <option value="-price" {% if order == "-price" %} selected {% endif %}>قیمت (زیاد به کم)</option>
                  <option value="-added_date" {% if order == "-added_date" %} selected {% endif %}>جدیدترین</option>
                  <option value="added_date" {% if order == "added_date" %} selected {% endif %}>قدیمی ترین</option>
                </select>
              </div>
            </form>
            <div class="col-sm-1 text-right">
              <label class="control-label" for="input-limit">نمایش :</label>
            </div>
            <div class="col-sm-2 text-right">
              <select id="input-limit" class="form-control">
                <option value="" selected="selected">20</option>
                <option value="">25</option>
                <option value="">50</option>
                <option value="">75</option>
                <option value="">100</option>
              </select>
            </div>
          </div>
        </div>
        <br />
        <div class="row products-category">
          {% for product in page_obj %}
          <div class="product-layout product-list col-xs-12">
            <div class="product-thumb">
              <div class="image"><a href="{{ product.get_absolute_url }}"><img src="{{ product.miniimage.url }}"
                    alt="{{product.name}}" title="{{product.name}}" class="img-responsive" /></a></div>
              <div>
                <div class="caption">
                  <h4><a href="{{ product.get_absolute_url }}"> کد محصول : {{product.id}}</a></h4>
                  <h4><a href="{{ product.get_absolute_url }}"> نام محصول : {{product.name}} </a></h4>
                  <p class="description"> توضیحات : {{ product.description }}</p>
                  <p class="price">
                    {% if product.discount_price %}
                    <li style="list-style-type: none;"><span class="price-new">قیمت :{{product.discount_price}}
                        تومان</span></li>
                    <li style="list-style-type: none;"><span class="price-old">قیمت :{{product.price}} تومان</span></li>
                    <span class="saving">
                      {{ product.save_percent }}%
                    </span>
                    {% else %}
                    <li style="list-style-type: none;"><span class="price-new">قیمت :{{product.price}} تومان</span></li>
                    <li style="list-style-type: none;"><br></li>
                    {% endif %}
                    <span class="price-tax">بدون مالیات : 90000 تومان</span>
                  </p>
                </div>
                <div class="button-group">
                  {% if product.label == 'ناموجود' %}
                  <a class="btn disabled" href="{{ product.get_add_to_cart_url }}"><button class="btn-danger"
                          type="button" onClick=""><span>ناموجود</span></button></a>
                  {% else %}
                  <a href="{{ product.get_add_to_cart_url }}"><button class="btn-primary"
                          type="button"><span>افزودن به سبد</span></button></a>
                  {% endif %}
                  <div class="add-to-links">
                      <a href="{{ product.get_add_to_wishlist_url }}"><button type="button"
                              data-toggle="tooltip" title="افزودن به علاقه مندی ها" onClick=""><i
                                  class="fa fa-heart"></i></button></a>
                      <a href="{{ product.get_add_to_compare_url }}"><button type="button"
                              data-toggle="tooltip" title="افزودن به مقایسه" onClick=""><i
                                  class="fa fa-exchange"></i></button></a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="row">
          <div class="col-sm-6 text-left">
            <nav aria-label="Page navigation example">
              <ul class="pagination">
                {% if page_obj.has_previous %}
                <li class="page-item"><a class="page-link" href="?page=1">اولین</a></li>
                <!-- <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a></li> -->
                <li class="page-item"><a class="page-link"
                    href="?page={{ page_obj.previous_page_number }}&?order={{order}}">{{ page_obj.previous_page_number }}</a>
                </li>

                {% endif %}
                <li class="page-item active"><a class="page-link">{{ page_obj.number }}</a></li>

                {% if page_obj.has_next %}
                <li class="page-item"><a class="page-link"
                    href="?page={{ page_obj.next_page_number }}&?order={{order}}">{{ page_obj.next_page_number }}</a>
                </li>
                <!-- <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">بعدی</a></li> -->
                <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}">آخرین</a>
                </li>
                {% endif %}
              </ul>
            </nav>
          </div>
          <!-- <div class="col-sm-6 text-right">نمایش 1 تا 12 از 15 (مجموع 2 صفحه)</div> -->
        </div>
      </div>
      <!--Middle Part End -->
    </div>
  </div>
</div>
{% endblock %}