blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('<pk>/', BlogDetailView.as_view(), name='blog-detail'),
]

tpshop/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include,re_path
from django.conf.urls.static import static
from product.views import handler404
from django.contrib import admin
from api.views import TestView
from tpshop import settings



handler404 = handler404
# handler500 = myapp.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root':"path\to\your\static\folder"}),
    path('accounts/', include('allauth.urls')),
    path('',include('product.urls'),name='product'),
    path('cart/',include('cart.urls'),name='cart'),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/',TestView.as_view(),name='api'),
    path('captcha/', include('captcha.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

userprofile/urls.py
from django.urls import path, re_path
from .views import userprofile,OrderDetail,UserOrders,UserAddresses,UserComments,PersonalInfo,datepicker

app_name = 'userprofile'

urlpatterns = [
    path('', userprofile, name='userprofile'),
    path('order-detail/<pk>', OrderDetail, name='order-detail'),
    path('user-orders/', UserOrders, name='user-orders'),
    path('addresses/', UserAddresses, name='user-addresses'),
    path('comments/', UserComments, name='user-comments'),
    path('personal-info/', PersonalInfo, name='personal-info'),
    path('datepicker/', datepicker, name='datepicker'),

    

]

userprofile/models.py
from django.db import models
from django.conf import settings
from django.shortcuts import reverse
from persiantools.jdatetime import JalaliDate

# Create your models here.

class UserProfile(models.Model):
    user=models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    first_name=models.CharField(max_length=255,null=True,blank=True)
    last_name=models.CharField(max_length=255,null=True,blank=True)
    job=models.CharField(max_length=255,null=True,blank=True)
    avatar=models.ImageField(upload_to='profile/',null=True,blank=True)
    phone_number=models.CharField(max_length=11,null=True,blank=True)
    email=models.CharField(max_length=255,null=True,blank=True)
    birth_date=models.DateField(null=True,blank=True)
    credit_card=models.CharField(max_length=16,null=True,blank=True)

    def __str__(self):
        return self.first_name

    def jalali_date(self):
        return JalaliDate(self.birth_date).strftime("%Y/%m/%d")

    def get_absulote_url (self):
        return reverse('userprofile:userprofile')

userprofile/forms.py
from django import forms
from .models import UserProfile
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
import datetime
class FirstLastNameForm(forms.Form):
    first_name=forms.CharField(max_length=200,label='نام',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    last_name=forms.CharField(max_length=200,label='نام خانوادگی',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))

class EmailForm(forms.Form):
    email=forms.EmailField(label='ایمیل',widget=forms.EmailInput(attrs={
        'class':'form-control',
    }))

class PhoneForm(forms.Form):
    phone_number=forms.CharField(max_length=11, label='شماره موبایل',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))

this_year=datetime.date.today().year
YEARS=[i for i in range(this_year,this_year-90,-1)]
class BirthDateForm(forms.Form):
    birth_date=forms.DateField(label='تاریخ تولد',help_text='زبان خود را به انگلیسی تغییر دهید', widget=forms.SelectDateWidget(attrs={
        # 'placeholder':'2006-10-25',
        'class':'form-control',
    },years=YEARS))

class ImageForm(forms.Form):
    image=forms.ImageField(label='تصویر کابر')

class JobForm(forms.Form):
    job=forms.CharField(label='شغل')

class CardForm(forms.Form):
    card=forms.CharField(label='شماره کارت')

userprofile/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from cart.models import Order,OrderItem,CheckoutInfo
from django.contrib.auth.decorators import login_required
from product.models import ProductComment
from .forms import FirstLastNameForm,EmailForm,PhoneForm,BirthDateForm,ImageForm,JobForm,CardForm
from .models import UserProfile
# Create your views here.

@login_required
def userprofile (request):

    # user_id=request.user.id
    # current_user=get_object_or_404(User,id=pk)
    orders=Order.objects.filter(user=request.user)
    context={
        # 'current_user': current_user,
        'orders':orders
    }
    return render(request,'profile_page.html',context)

@login_required
def OrderDetail(request,pk):
    userorder=get_object_or_404(Order,id=pk)
    orderitems=OrderItem.objects.filter(order=userorder)
    context={
        'userorder':userorder,
        'orderitems':orderitems
    }
    return render(request,'order-detail.html',context)

@login_required
def UserOrders(request):
    userorders=Order.objects.filter(user=request.user)
    context={
        'userorders':userorders
    }
    return render(request,'userorders.html',context)

@login_required
def UserAddresses(request):
    infos=CheckoutInfo.objects.filter(user=request.user)
    context={
        'infos': infos
    }
    return render(request,'user-address.html',context)

@login_required
def UserComments(request):
    comments=ProductComment.objects.filter(user=request.user)
    context={
        'comments': comments
    }
    return render(request,'user-comments.html',context)

@login_required
def PersonalInfo(request):
    if request.method == "POST":
        userprofile=UserProfile.objects.get(user=request.user)
        name_form = FirstLastNameForm(request.POST or None)
        email_form=EmailForm(request.POST or None)
        phone_form=PhoneForm(request.POST or None)
        birth_date_form=BirthDateForm(request.POST or None)
        job_form=JobForm(request.POST or None)
        card_form=CardForm(request.POST or None)
        image_form=ImageForm(request.POST ,request.FILES)
        if name_form.is_valid():
            first_name = name_form.cleaned_data.get('first_name')
            last_name=name_form.cleaned_data.get('last_name')
            if UserProfile.objects.filter(user=request.user).exists():
                userprofile.first_name=first_name
                userprofile.last_name=last_name
                userprofile.save()
        if email_form.is_valid():
            userprofile.email = email_form.cleaned_data.get('email')
            userprofile.save() 
        if phone_form.is_valid():
            userprofile.phone_number = phone_form.cleaned_data.get('phone_number')
            userprofile.save()
        if birth_date_form.is_valid():
            userprofile.birth_date = birth_date_form.cleaned_data.get('birth_date')
            userprofile.save() 
        if image_form.is_valid():
            userprofile.avatar = image_form.cleaned_data.get('image')
            userprofile.save()
        if job_form.is_valid():
            userprofile.job = job_form.cleaned_data.get('job')
            userprofile.save()
        if card_form.is_valid():
            userprofile.credit_card = card_form.cleaned_data.get('card')
            userprofile.save()
    else:
        name_form = FirstLastNameForm()
        email_form=EmailForm()
        phone_form=PhoneForm()
        birth_date_form=BirthDateForm()
        image_form=ImageForm()
        job_form=JobForm()
        card_form=CardForm()

    context={
        'name_form':FirstLastNameForm(initial={
            'first_name':request.user.userprofile.first_name,
            'last_name':request.user.userprofile.last_name    
        }),
        'email_form':EmailForm(initial={
            'email':request.user.userprofile.email,
        }),
        'phone_form':PhoneForm(initial={
            'phone_number':request.user.userprofile.phone_number,
        }),
        'birth_date_form':BirthDateForm(),
        'image_form':ImageForm(),
        'job_form':JobForm(initial={
            'job':request.user.userprofile.job,
        }),
        'card_form':CardForm(initial={
            'card':request.user.userprofile.credit_card,
        }),
    }
    return render(request,'personal-info.html',context)

def datepicker(request):
    return render(request,'datepicker.html',{})

userprofile/templates/datepicker.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>jQuery UI Datepicker with Twitter Bootstrap Theme</title>
        <!-- <link rel="stylesheet" href="css/bootstrap.min.css" /> -->
        <!-- <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.min.css' %}" /> -->
        <style>body{margin:2em}</style>
        <style>
            table { 
            width: 100%; 
            border-collapse: collapse; 
            }
            /* Zebra striping */
            tr:nth-of-type(odd) { 
            background: #eee; 
            }
            th { 
            background: #333; 
            color: white; 
            font-weight: bold; 
            }
            td, th { 
            padding: 6px; 
            border: 1px solid #ccc; 
            text-align: left; 
            }

            @media 
            only screen and (max-width: 760px),
            (min-device-width: 768px) and (max-device-width: 1024px)  {

            /* Force table to not be like tables anymore */
            table, thead, tbody, th, td, tr { 
                display: block; 
            }
            
            /* Hide table headers (but not display: none;, for accessibility) */
            thead tr { 
                position: absolute;
                top: -9999px;
                left: -9999px;
            }
            
            tr { border: 1px solid #ccc; }
            
            td { 
                /* Behave  like a "row" */
                border: none;
                border-bottom: 1px solid #eee; 
                position: relative;
                padding-left: 50%; 
            }
            
            td:before { 
                /* Now like a table header */
                position: absolute;
                /* Top/left values mimic padding */
                top: 6px;
                left: 6px;
                width: 45%; 
                padding-right: 10px; 
                white-space: nowrap;
            }
            
            /*
            Label the data
            */
            td:nth-of-type(1):before { content: "First Name"; }
            td:nth-of-type(2):before { content: "Last Name"; }
            td:nth-of-type(3):before { content: "Job Title"; }
            td:nth-of-type(4):before { content: "Favorite Color"; }
            td:nth-of-type(5):before { content: "Wars of Trek?"; }
            td:nth-of-type(6):before { content: "Secret Alias"; }
            td:nth-of-type(7):before { content: "Date of Birth"; }
            td:nth-of-type(8):before { content: "Dream Vacation City"; }
            td:nth-of-type(9):before { content: "GPA"; }
            td:nth-of-type(10):before { content: "Arbitrary Data"; }
        }
        </style>
        
        <link rel="stylesheet" href="{% static 'css/persian-datepicker.css' %}"/>
        <script src="{% static 'js/jquery.js' %}"></script> 
        <script src="{% static 'js/persian-date.js' %}"></script> 
        <script src="{% static 'js/persian-datepicker.js' %}"></script> 

    </head>
    <body>
        <h1>jQuery UI Datepicker with Twitter Bootstrap Theme</h1>
        <script type="text/javascript">
            $(document).ready(function() {
              $(".example1").pDatepicker();
              $(calendarType)='persian';
            });
          </script> 
           
          <input type="text" class="example1" />

          <table>
            <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Job Title</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>James</td>
                <td>Matman</td>
                <td>Chief Sandwich Eater</td>
            </tr>
            <tr>
                <td>The</td>
                <td>Tick</td>
                <td>Crimefighter Sorta</td>
            </tr>
            </tbody>
        </table>

        <!-- <form>
            <div class="control-group">
                <label class="control-label" for="datepicker0">Datepicker</label>
                <div class="controls">
                    <input id="datepicker0" type="text">
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker1">Datepicker with bootstrap icon button</label>
                <div class="controls">
                    <div class="input-append">
                        <input id="datepicker1" class="input-small" type="text">
                        <button id="datepicker1btn" class="btn" type="button"><i class="icon-calendar"></i></button>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker2">Datepicker with other months selectable (jQuery option)</label>
                <div class="controls">
                    <input type="text" id="datepicker2" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker3">Datepicker with 3 months and button panel (jQuery option)</label>
                <div class="controls">
                    <input type="text" id="datepicker3" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker4">Datepicker with change month/year (jQuery option)</label>
                <div class="controls">
                    <input type="text" id="datepicker4" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker5">Datepicker with limited selection to within the next 14 days (jQuery option)</label>
                <div class="controls">
                    <input type="text" id="datepicker5" />
                </div>
            </div>
            <div class="control-group">
                <label class="control-label" for="datepicker6">Datepicker with RTL and date format (jQuery option)</label>
                <div class="controls">
                    <input id="datepicker6" type="text">
                </div>
            </div>
        </form>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
        <script src="{% static 'js/bootstrap-datepicker.min.js' %}"></script>
        <script src="{% static 'js/bootstrap-datepicker.fa.min.js' %}"></script>
        <script>
            $(document).ready(function() {
                $("#datepicker0").datepicker();
            
                $("#datepicker1").datepicker();
                $("#datepicker1btn").click(function(event) {
                    event.preventDefault();
                    $("#datepicker1").focus();
                })
            
                $("#datepicker2").datepicker({
                    showOtherMonths: true,
                    selectOtherMonths: true
                });
            
                $("#datepicker3").datepicker({
                    numberOfMonths: 3,
                    showButtonPanel: true
                });
            
                $("#datepicker4").datepicker({
                    changeMonth: true,
                    changeYear: true
                });
            
                $("#datepicker5").datepicker({
                    minDate: 0,
                    maxDate: "+14D"
                });
            
                $("#datepicker6").datepicker({
                    isRTL: true,
                    dateFormat: "d/m/yy"
                });
            });
        </script> -->
    </body>
</html>

userprofile/templates/order-detail.html
{% extends 'base1.html' %}
{% load static %}


{% block head %}
    <link href="{% static 'css/profile_page_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row" style="margin-top: 40px;">

            <div class="col-sm-3">
                <div>
                    <img src="{{ request.user.userprofile.avatar.url }}" alt="image" class="profile-img">
                    <p class="user">{{ request.user.userprofile.first_name }} {{ request.user.userprofile.last_name }}</p>

                    {% include 'profile_page_components/profile_sidebar_component.html' %}

                </div>
            </div>
            
            <div class="col-sm-9" style="padding-right: 5rem;">
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <td class="d-flex">
                                <div style="padding-left: 1rem;" onclick="window.history.back()"><i class="fa fa-arrow-right" aria-hidden="true"></i></div>
                                <div style="padding-left: 4rem;font-weight: bold;font-size: larger;">
                                    جزییات سفارش</div>
                                <div > ۲۴ مرداد ۱۳۹۹</div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <div class="d-flex">
                                <div style="padding-left: 4rem;">تحویل گیرنده : ابراهیم آرون</div>
                                <div style="padding-left: 4rem;">شماره تماس : ۰۹۹۱۸۷۹۷۳۷۶</div>
                                </div>
                                <div style="padding-left: 4rem;padding-top: 2rem;"> آدرس : تهران خیابان آزادی خیابان جمالزاده</div>
                            </td>
                        </tr>
                        <tr>
                            <td class="d-flex" style="border-bottom:1px solid #ddd;">
                                <div style="padding-left: 5rem;"> مبلغ کل : ۲۸۶۰۰۰ تومان</div>
                                <div> مبلغ تخفیف : ۲۸۶۰۰۰ تومان</div>
                            </td>
                        </tr>
                    </table>
                </div>
                
                <div class="table-responsive">
                    <table class="table table-bordered ">
                        <tr>
                            <td>
                                <div>مرسوله ۱ ارسال عادی</div>
                                <div style="padding-top: 2rem;">تحویل: سه شنبه ۲۸ مرداد</div>
                                <div style="padding-top: 2rem;">مبلغ کل این مرسوله : ۲۸۶۳۸۰ تومان</div>
                            </td>
                        </tr>
                        <div class="row products-category">
                                {% for item in orderitems %}
                                <tr>
                                    <td>
                                        <div class="product-layout product-list col-xs-12">
                                            <div class="product-thumb">
                                                <div class="image" style="padding-right: 2rem;"><a href="{{ item.get_absolute_url }}"><img src="{{ item.product.miniimage.url }}"
                                                    alt="{{item.product.name}}" title="{{product.name}}" class="img-responsive" /></a>
                                                </div>
                                                <div class="caption">
                                                    <h4><a href="{{ product.get_absolute_url }}"> کد محصول : {{item.product.id}}</a></h4>
                                                    <h4><a href="{{ product.get_absolute_url }}"> نام محصول : {{item.product.name}} </a></h4>
                                                    <p class="price">
                                                    {% if item.product.discount_price %}
                                                    <li style="list-style-type: none;"><span class="price-new">قیمت :{{item.product.discount_price}}
                                                        تومان</span></li>
                                                    <li style="list-style-type: none;"><span class="price-old">قیمت :{{item.product.price}} تومان</span></li>
                                                    <span class="saving">
                                                        {{ item.product.save_percent }}%
                                                    </span>
                                                    {% else %}
                                                    <li style="list-style-type: none;"><span class="price-new">قیمت :{{item.product.price}} تومان</span></li>
                                                    <li style="list-style-type: none;"><br></li>
                                                    {% endif %}
                                                    </p>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                                {% endfor %}
                        </div>
                    </table>
                </div>

            </div>
        </div>
    </div>
</section>
{% endblock %}

userprofile/templates/profile_page.html
{% extends 'base1.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'css/profile_page_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <section>
        <div class="container">
            <div class="row" style="margin-top: 40px;">
                <div class="col-sm-3">
                    <div>
                        <img src="{{ request.user.userprofile.avatar.url }}" alt="image" class="profile-img">
                        <p class="user">{{ request.user.userprofile.first_name }} {{ request.user.userprofile.last_name }}</p>
    
                        {% include 'profile_page_components/profile_sidebar_component.html' %}
    
                    </div>
                </div>


                <div class="col-sm-9">

                    <table class="table-bordered" style="width:100%">
                        <caption>اطلاعات شخصی</caption>
                        <tr>
                            <td class="col-one">نام و نام خانوادگی : <span
                                    style="color: #2a6496">{{ request.user.userprofile.first_name }} {{ request.user.userprofile.last_name }}</span>
                            </td>
                            <td class="col-two">ایمیل : <span style="color: #2a6496;">{{ request.user.userprofile.email }}</span>
                            </td>
                        </tr>
                        <tr>
                            <td class="col-one">شماره تلفن همراه : <span style="color: #2a6496;">
                                {% if request.user.userprofile.phone_number is None %} &nbsp; {% else %}
                                    {{ request.user.userprofile.phone_number }} {% endif %} </span>
                            </td>

                            <td class="col-two">تاریخ تولد : <span style="color: #2a6496;">
                                {% if request.user.userprofile.jalali_date is None %} &nbsp; {% else %}
                                    {{ request.user.userprofile.jalali_date }}{% endif %}</span>
                            </td>
                        </tr>
                    </table>
                    <div style="text-align: center;padding: 2rem;">
                        <a href="{% url 'userprofile:personal-info' %}" style="color: red;font-weight: bold;">
                            <i class="fa fa-edit" style="font-size: 18px;color: red;"></i>
                            ویرایش اطلاعات شخصی
                        </a>
                    </div>
                    <table class="mytable table-bordered" style="width:100%; margin-top: 50px;">
                        <caption>لیست سفارشات</caption>
                        <tr>
                            <th class="num">#</th>
                            <th class="order-num">شماره سفارش</th>
                            <th class="order-date">تاریخ ثبت سفارش</th>
                            <th class="paying-price">مبلغ قابل پرداخت</th>
                            <th class="total-price">مبلغ کل</th>
                            <th class="paying-status">عملیات پرداخت</th>
                            <th class="details">جزییات</th>
                        </tr>
                        {% for order in orders %}
                            {% if forloop.counter <= 3 %}
                        <tr>
                            <td class="num">{{ forloop.counter }}</td>
                            <td class="order-num">{{ order.id }}</td>
                            <td class="order-date">{{ order.jalali_ordered_date }}</td>
                            <td class="paying-price">{{ order.get_total }}</td>
                            <td class="total-price">{{ order.get_total_with_coupon }}</td>
                            <td class="paying-status">{% if ordered %}پرداخت موفق {%else%} پرداخت ناموفق {%endif%}</td>
                            <td class="details"><a href="{% url 'userprofile:order-detail' pk=order.id %}"><i class="fa fa-hand-o-left"
                                                              style="font-size: 20px;"></i></a></td>
                        </tr>
                            {% endif %}
                        {% endfor %}

                    </table>

                    <div style="text-align: center;font-weight: bold;padding: 2rem;"><a href="{% url 'userprofile:user-orders' %}" style="color:#3e7cb4;">مشاهده تمام سفارشات</a></div>

                </div>

            </div>
        </div>
    </section>

{% endblock %}

userprofile/templates/userorders.html
{% extends 'base1.html' %}
{% load static %}

{% block head %}
    <link href="{% static 'css/profile_page_styles.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<section>
    <div class="container">
        <div class="row" style="margin-top: 40px;">

            <div class="col-sm-3">
                <div>
                    <img src="{{ request.user.userprofile.avatar.url }}" alt="image" class="profile-img">
                    <p class="user">{{ request.user.userprofile.first_name }} {{ request.user.userprofile.last_name }}</p>

                    {% include 'profile_page_components/profile_sidebar_component.html' %}

                </div>
            </div>

            <div class="col-sm-9">
                <table class="mytable table-bordered" style="width:100%; margin-top: 50px;">
                    <caption>لیست سفارشات</caption>
                    <tr>
                        <th class="num">#</th>
                        <th class="order-num">شماره سفارش</th>
                        <th class="order-date">تاریخ ثبت سفارش</th>
                        <th class="paying-price">مبلغ قابل پرداخت</th>
                        <th class="total-price">مبلغ کل</th>
                        <th class="paying-status">عملیات پرداخت</th>
                        <th class="details">جزییات</th>
                    </tr>
                    {% for order in userorders %}
                    <tr>
                        <td class="num">{{ forloop.counter }}</td>
                        <td class="order-num">{{ order.id }}</td>
                        <td class="order-date">{{ order.jalali_ordered_date }}</td>
                        <td class="paying-price">{{ order.get_total }}</td>
                        <td class="total-price">{{ order.get_total_with_coupon }}</td>
                        <td class="paying-status">{% if order.ordered %}پرداخت موفق {%else%} پرداخت ناموفق {%endif%}</td>
                        <td class="details"><a href="{% url 'userprofile:order-detail' pk=order.id %}"><i class="fa fa-hand-o-left"
                                                        style="font-size: 20px;"></i></a></td>
                    </tr>
                    {% endfor %}

                </table>
            </div> 
        </div>
    </div>
</section>
{% endblock %}