blog/urls.py
from django.urls import path
from .views import BlogListView, BlogDetailView

app_name = 'blog'

urlpatterns = [
    path('', BlogListView.as_view(), name='blog'),
    path('<pk>/', BlogDetailView.as_view(), name='blog-detail'),
]

product/urls.py
from django.urls import path, re_path
from .views import (
    home,
    ProductDetailView,
    productlist,
    contact,
    product_category,
    about_us,
    CompareView,
    add_to_compare,
    remove_from_compare,
    search,
    WishView,
    add_to_wishlist,
    remove_from_wishlist,
    product_subcategory,
    sitemap,
    faq,
)

app_name = 'product'

urlpatterns = [
    path('', home, name='home'),
    path('product/<int:pk>/<slug>/',
         ProductDetailView.as_view(), name='product-detail'),
    path('products/', productlist, name='products'),
    path('contact-us/', contact, name='contact-us'),
    path('products/<int:pk>/<slug>/', product_category, name='category'),
    path('products/<slug>/<int:pk>/<category>/',
         product_subcategory, name='subcategory'),
    path('about-us/', about_us, name='about-us'),
    path('sitemap/', sitemap, name='sitemap'),
    path('compare/', CompareView.as_view(), name='compare'),
    path('add_to_compare/<pk>', add_to_compare, name='add_to_compare'),
    path('remove_from_compare/<pk>', remove_from_compare,
         name='remove_from_compare'),
    path('search/', search, name='search'),
    path('wishlist/', WishView.as_view(), name='wishlist'),
    path('add_to_wishlist/<pk>', add_to_wishlist, name='add_to_wishlist'),
    path('remove_from_wishlist/<pk>', remove_from_wishlist,
         name='remove_from_wishlist'),
    path('faq/', faq, name='faq'),
]

tpshop/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include,re_path
from django.conf.urls.static import static
from product.views import handler404
from django.contrib import admin
from api.views import TestView
from tpshop import settings



handler404 = handler404
# handler500 = myapp.views.handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    # re_path(r'^static/(?P<path>.*)$', 'django.views.static.serve',{'document_root':"path\to\your\static\folder"}),
    path('accounts/', include('allauth.urls')),
    path('',include('product.urls'),name='product'),
    path('cart/',include('cart.urls'),name='cart'),
    path('api-auth/', include('rest_framework.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/',TestView.as_view(),name='api'),
    path('captcha/', include('captcha.urls')),
    path('ratings/', include('star_ratings.urls', namespace='ratings')),
    path('hitcount/', include(('hitcount.urls', 'hitcount'), namespace='hitcount')),
]

if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

userprofile/urls.py
from django.urls import path, re_path
from .views import userprofile,OrderDetail,UserOrders,UserAddresses,UserComments,PersonalInfo,datepicker

app_name = 'userprofile'

urlpatterns = [
    path('', userprofile, name='userprofile'),
    path('order-detail/<pk>', OrderDetail, name='order-detail'),
    path('user-orders/', UserOrders, name='user-orders'),
    path('addresses/', UserAddresses, name='user-addresses'),
    path('comments/', UserComments, name='user-comments'),
    path('personal-info/', PersonalInfo, name='personal-info'),
    path('datepicker/', datepicker, name='datepicker'),

    

]

product/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify
from django.shortcuts import reverse
from django.conf import settings
from star_ratings.models import Rating
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericForeignKey
from hitcount.models import HitCountMixin, HitCount
from django.contrib.contenttypes.fields import GenericRelation


from persiantools.jdatetime import JalaliDate
# Create your models here.

LABEL_CHOICES = (
    ('موجود', 'موجود'),
    ('ناموجود', 'ناموجود'),
)


class FeatureManager(models.Manager):
    def are_featured(self):
        featured_products = []
        for product in Product.objects.all():
            if product.is_featured():
                featured_products.append(product.id)
        nfeatured = Product.objects.filter(id__in=featured_products)[:6]
        # use your method to filter results
        return nfeatured


class Category(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(null=True, blank=True,
                            default='test', allow_unicode=True)
    image = models.ImageField(upload_to='category/',null=True)

    class Meta:
        verbose_name = "Category"
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('product:category', kwargs={'pk': self.id, 'slug': self.slug})


class Subcategory(models.Model):
    title = models.CharField(max_length=200)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, related_name='subcategory')
    slug = models.SlugField(null=True, blank=True,
                            default='test', allow_unicode=True)

    class Meta:
        verbose_name = "Subcategory"
        verbose_name_plural = "Subcategories"

    def __str__(self):
        return self.title

    def get_category_slug(self):
        category_slug = slugify(self.category, allow_unicode=True)
        return category_slug

    def get_absolute_url(self):
        return reverse('product:subcategory', kwargs={'category': self.get_category_slug(), 'pk': self.id, 'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title, allow_unicode=True)
        return super().save(*args, **kwargs)


class Product (models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField()
    price = models.IntegerField()
    discount_price = models.IntegerField(null=True, blank=True)
    miniimage = models.ImageField(upload_to='products/', null=True, blank=True)
    subcategory = models.ForeignKey(
        Subcategory, on_delete=models.CASCADE, null=True, related_name='products')
    label = models.CharField(choices=LABEL_CHOICES, default='M', max_length=8)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, related_name='products')
    added_date = models.DateTimeField(auto_now_add=True)
    slug = models.SlugField(null=True, blank=True,
                            default='test', allow_unicode=True)
    hit_count_generic = GenericRelation(HitCount, object_id_field='object_pk',
                                        related_query_name='hit_count_generic_relation')
    objects = FeatureManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product-detail', kwargs={'pk': self.id, 'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name, allow_unicode=True)
        return super().save(*args, **kwargs)

    def save_percent(self):
        if self.discount_price:
            saving = int(((self.price - self.discount_price)/self.price) * 100)
            return saving
        return 0

    def get_label_color(self):
        if self.label == 'موجود':
            return 'instock'
        else:
            return 'nostock'

    def is_featured(self):
        save = self.save_percent()
        if save >= 5:
            return True
        else:
            return False

    def get_add_to_cart_url(self):
        return reverse('cart:add_to_cart', kwargs={'pk': self.id})

    def get_remove_from_cart_url(self):
        return reverse('cart:remove_from_cart', kwargs={'pk': self.id})

    def get_add_to_compare_url(self):
        return reverse('product:add_to_compare', kwargs={'pk': self.id})

    def get_remove_from_compare_url(self):
        return reverse('product:remove_from_compare', kwargs={'pk': self.id})

    def get_add_to_wishlist_url(self):
        return reverse('product:add_to_wishlist', kwargs={'pk': self.id})

    def get_remove_from_wishlist_url(self):
        return reverse('product:remove_from_wishlist', kwargs={'pk': self.id})


class Images (models.Model):
    product = models.ForeignKey(
        Product, default=None, on_delete=models.CASCADE, related_name='images')
    miniimage = models.ImageField(upload_to='products/', blank=True)


class CompareItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name


class Compare(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    products = models.ManyToManyField(CompareItem)

    def __str__(self):
        return self.user.username


class WishItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return self.product.name


class Wishlist(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    products = models.ManyToManyField(WishItem)

    def __str__(self):
        return self.user.username


class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()

    def __str__(self):
        return self.name


class ProductComment(models.Model):
    user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    username = models.CharField(max_length=200)
    message = models.TextField()
    product = models.ForeignKey(
        Product, on_delete=models.CASCADE, related_name='comments')
    date = models.DateField(auto_now_add=True)
    approved = models.BooleanField(default=False)
    parent = models.ForeignKey(
        'self', on_delete=models.CASCADE, blank=True, null=True, related_name='replies')

    def __str__(self):
        return self.username

    def convert_jalali(self):
        return JalaliDate(self.date).strftime("%Y/%m/%d")


class Hit(models.Model):
    date = models.DateTimeField(auto_now=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

userprofile/forms.py
from django import forms
from .models import UserProfile
from jalali_date.fields import JalaliDateField, SplitJalaliDateTimeField
from jalali_date.widgets import AdminJalaliDateWidget, AdminSplitJalaliDateTime
import datetime
class FirstLastNameForm(forms.Form):
    first_name=forms.CharField(max_length=200,label='نام',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))
    last_name=forms.CharField(max_length=200,label='نام خانوادگی',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))

class EmailForm(forms.Form):
    email=forms.EmailField(label='ایمیل',widget=forms.EmailInput(attrs={
        'class':'form-control',
    }))

class PhoneForm(forms.Form):
    phone_number=forms.CharField(max_length=11, label='شماره موبایل',widget=forms.TextInput(attrs={
        'class':'form-control',
    }))

this_year=datetime.date.today().year
YEARS=[i for i in range(this_year,this_year-90,-1)]
class BirthDateForm(forms.Form):
    birth_date=forms.DateField(label='تاریخ تولد',help_text='زبان خود را به انگلیسی تغییر دهید', widget=forms.SelectDateWidget(attrs={
        # 'placeholder':'2006-10-25',
        'class':'form-control',
    },years=YEARS))

class ImageForm(forms.Form):
    image=forms.ImageField(label='تصویر کابر')

class JobForm(forms.Form):
    job=forms.CharField(label='شغل')

class CardForm(forms.Form):
    card=forms.CharField(label='شماره کارت')

userprofile/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.contrib.auth.models import User
from cart.models import Order,OrderItem,CheckoutInfo
from django.contrib.auth.decorators import login_required
from product.models import ProductComment
from .forms import FirstLastNameForm,EmailForm,PhoneForm,BirthDateForm,ImageForm,JobForm,CardForm
from .models import UserProfile
# Create your views here.

@login_required
def userprofile (request):

    # user_id=request.user.id
    # current_user=get_object_or_404(User,id=pk)
    orders=Order.objects.filter(user=request.user)
    context={
        # 'current_user': current_user,
        'orders':orders
    }
    return render(request,'profile_page.html',context)

@login_required
def OrderDetail(request,pk):
    userorder=get_object_or_404(Order,id=pk)
    orderitems=OrderItem.objects.filter(order=userorder)
    context={
        'userorder':userorder,
        'orderitems':orderitems
    }
    return render(request,'order-detail.html',context)

@login_required
def UserOrders(request):
    userorders=Order.objects.filter(user=request.user)
    context={
        'userorders':userorders
    }
    return render(request,'userorders.html',context)

@login_required
def UserAddresses(request):
    infos=CheckoutInfo.objects.filter(user=request.user)
    context={
        'infos': infos
    }
    return render(request,'user-address.html',context)

@login_required
def UserComments(request):
    comments=ProductComment.objects.filter(user=request.user)
    context={
        'comments': comments
    }
    return render(request,'user-comments.html',context)

@login_required
def PersonalInfo(request):
    if request.method == "POST":
        userprofile=UserProfile.objects.get(user=request.user)
        name_form = FirstLastNameForm(request.POST or None)
        email_form=EmailForm(request.POST or None)
        phone_form=PhoneForm(request.POST or None)
        birth_date_form=BirthDateForm(request.POST or None)
        job_form=JobForm(request.POST or None)
        card_form=CardForm(request.POST or None)
        image_form=ImageForm(request.POST ,request.FILES)
        if name_form.is_valid():
            first_name = name_form.cleaned_data.get('first_name')
            last_name=name_form.cleaned_data.get('last_name')
            if UserProfile.objects.filter(user=request.user).exists():
                userprofile.first_name=first_name
                userprofile.last_name=last_name
                userprofile.save()
        if email_form.is_valid():
            userprofile.email = email_form.cleaned_data.get('email')
            userprofile.save() 
        if phone_form.is_valid():
            userprofile.phone_number = phone_form.cleaned_data.get('phone_number')
            userprofile.save()
        if birth_date_form.is_valid():
            userprofile.birth_date = birth_date_form.cleaned_data.get('birth_date')
            userprofile.save() 
        if image_form.is_valid():
            userprofile.avatar = image_form.cleaned_data.get('image')
            userprofile.save()
        if job_form.is_valid():
            userprofile.job = job_form.cleaned_data.get('job')
            userprofile.save()
        if card_form.is_valid():
            userprofile.credit_card = card_form.cleaned_data.get('card')
            userprofile.save()
    else:
        name_form = FirstLastNameForm()
        email_form=EmailForm()
        phone_form=PhoneForm()
        birth_date_form=BirthDateForm()
        image_form=ImageForm()
        job_form=JobForm()
        card_form=CardForm()

    context={
        'name_form':FirstLastNameForm(initial={
            'first_name':request.user.userprofile.first_name,
            'last_name':request.user.userprofile.last_name    
        }),
        'email_form':EmailForm(initial={
            'email':request.user.userprofile.email,
        }),
        'phone_form':PhoneForm(initial={
            'phone_number':request.user.userprofile.phone_number,
        }),
        'birth_date_form':BirthDateForm(),
        'image_form':ImageForm(),
        'job_form':JobForm(initial={
            'job':request.user.userprofile.job,
        }),
        'card_form':CardForm(initial={
            'card':request.user.userprofile.credit_card,
        }),
    }
    return render(request,'personal-info.html',context)

def datepicker(request):
    return render(request,'datepicker.html',{})

userprofile/templates/profile_page_components/header_component.html
{% load static %}
{% url 'home' as home_url %}

<header id="header"><!--header-->

    <div class="header-bottom"><!--header-bottom-->
        <div class="container">
            <div class="row">

                {% include 'search_product_input_component.html' %}

                <div class="col-sm-9">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse"
                                data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>


                    <div class="mainmenu pull-right">
                        <ul class="nav navbar-nav collapse navbar-collapse">
                            <li><a href="{{ home_url }}"
                                   class="{% if request.path == home_url %}active{% endif %}">خانه</a></li>
                            <!--    <li class="dropdown sub-menu"><a href="#">فروشگـاه<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li class="dropdown sub-menu"><a href="shop.html">محصولات</a></li>
                                    <li><a href="product-details.html">جزئیات محصولات</a></li>
                                    <li><a href="checkout.html">پرداخت</a></li>
                                    <li><a href="cart.html">سبـد خریـد</a></li>
                                    <li><a href="login.html">ورود</a></li>
                                </ul>
                            </li> -->
                            <li class="dropdown active"><a href="#"
                                                           class="{% if is_active %}active{% endif %}">محصولات<i
                                    class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="{% url 'show_all_products' %}">مشاهده همه محصولات</a></li>
                                    {% for item in category_list %}
                                        <li><a href="{{ item.get_absolute_url }}">{{ item.title }}</a></li>
                                    {% endfor %}

                                </ul>
                            </li>
                            <li class="dropdown"><a href="#">اخبـار<i class="fa fa-angle-down"></i></a>
                                <ul role="menu" class="sub-menu">
                                    <li><a href="blog.html">آخریـن اخبـار</a></li>
                                    <li><a href="blog-single.html">صفحـه خبـر</a></li>
                                </ul>
                            </li>
                            <li><a href="About.html">درباره مـا</a></li>
                            <li><a href="contact-us.html">تماس با مـا</a></li>


                        </ul>
                    </div>
                </div>

            </div>
        </div>
    </div><!--/header-bottom-->

</header>

userprofile/templates/profile_page_components/profile_mainlayout.html
{% load static %}
{#{% load render_partial %}#}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="#">
    <meta name="author" content="">
    <title>حساب کاربری</title>
    {% include 'shared/_HeaderReferences.html' %}
    {% block header_ref %}
        <link href="{% static 'css/profile_page_styles.css' %}" rel="stylesheet">
    {% endblock %}
</head>

<body>

{% include 'profile_page_components/header_component.html'%}
{#{% render_partial 'header' %}#}

{% block content %}{% endblock %}

{% include 'shared/Footer.html' %}
{#{% render_partial 'footer' %}#}

{% include 'shared/_FooterReferences.html' %}
{% block footer_ref %}{% endblock %}

</body>
</html>

userprofile/templates/profile_page_components/profile_sidebar_component.html
<div class="panel-group category-products" id="accordian"><!--category-productsr-->


    <div class="panel panel-default">
        <div class="panel-heading">
            <h4><a href="{% url 'userprofile:userprofile' %}" class="a-tags1"><i class='fa fa-user my-panel-title'></i>حساب کاربری</a></h4>
            <h4><a href="{% url 'userprofile:user-orders' %}" class="a-tags1"><i class='fa fa-shopping-cart my-panel-title'></i> سفارش های من</a></h4>
            <h4><a href="{% url 'userprofile:user-comments' %}" class="a-tags1"><i class='fa fa-comments-o my-panel-title' style='font-size:18px'></i> نظرات</a></h4>
            <h4><a href="{% url 'userprofile:user-addresses' %}" class="a-tags1"><i class='fa fa-map-marker my-panel-title' style='font-size:18px'></i> آدرس ها</a></h4>
            <h4><a href="" class="a-tags1"><i class='fa fa-gift my-panel-title' style='font-size:18px'></i> کارت های هدیه</a></h4>
            <h4><a href="{% url 'product:wishlist' %}" class="a-tags1"><i class='fa fa-heart-o my-panel-title' style='font-size:18px'></i> لیست علاقه مندی</a></h4>
            <h4><a href="{% url 'userprofile:personal-info' %}" class="a-tags1"><i class='fa fa-user my-panel-title' style='font-size:18px'></i> ویرایش اطلاعات حساب کاربری</a></h4>
            <h4><a href="#" class="a-tags1"><i class='fa fa-key my-panel-title' style='font-size:18px'></i> تغییر کلمه عبور</a></h4>
            <h4><a href="#" class="a-tags1" style="color: brown;"><i class='fa fa-sign-out my-panel-title' style='font-size:18px;color: brown;'></i> خروج</a></h4>
        </div>
    </div>



</div><!--/category-products-->

userprofile/templates/profile_page_components/usermodal.html
<!-- NameModal -->
<div class="modal fade" id="namemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
        <h4 class="modal-title" id="exampleModalLabel">نام و نام خانوادگی
            <button class="close" data-dismiss="modal" aria-label="Close">
            <i class="fa fa-times" aria-hidden="true"></i>
            </button>
        </h4>
        </strong>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %} {{ name_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- EmailModal -->
<div class="modal fade" id="emailmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
        <h4 class="modal-title" id="exampleModalLabel">ایمیل
            <button class="close" data-dismiss="modal" aria-label="Close">
            <i class="fa fa-times" aria-hidden="true"></i>
            </button>
        </h4>
        </strong>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %} {{ email_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- PhoneModal -->
<div class="modal fade" id="phonemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
        <h4 class="modal-title" id="exampleModalLabel">شماره موبایل
            <button class="close" data-dismiss="modal" aria-label="Close">
            <i class="fa fa-times" aria-hidden="true"></i>
            </button>
        </h4>
        </strong>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %} {{ phone_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- BirthDateModal -->
<div class="modal fade" id="birthdatemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
        <h4 class="modal-title" id="exampleModalLabel">تاریخ تولد
            <button class="close" data-dismiss="modal" aria-label="Close">
            <i class="fa fa-times" aria-hidden="true"></i>
            </button>
        </h4>
        </strong>
            </div>
            <div class="modal-body">
                <form method="POST">
                    {% csrf_token %} {{ birth_date_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- ImageModal -->
<div class="modal fade" id="imagemodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
<h4 class="modal-title" id="exampleModalLabel">تاریخ تولد
<button class="close" data-dismiss="modal" aria-label="Close">
<i class="fa fa-times" aria-hidden="true"></i>
</button>
</h4>
</strong>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %} {{ image_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- JobModal -->
<div class="modal fade" id="jobmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
<h4 class="modal-title" id="exampleModalLabel">شغل
<button class="close" data-dismiss="modal" aria-label="Close">
<i class="fa fa-times" aria-hidden="true"></i>
</button>
</h4>
</strong>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %} {{ job_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="cardmodal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <strong>
<h4 class="modal-title" id="exampleModalLabel">شماره کارت
<button class="close" data-dismiss="modal" aria-label="Close">
<i class="fa fa-times" aria-hidden="true"></i>
</button>
</h4>
</strong>
            </div>
            <div class="modal-body">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %} {{ card_form }}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">بستن</button>
                <button type="submit" class="btn btn-primary" style="font-weight: 500;width: 90px;">ویرایش</button>
                </form>
            </div>
        </div>
    </div>
</div>